
version: "3.7"
services:
 ft_nm:
  build: 
   context: ./
   args:
    BUILD_DATE: 
  image: ft_malloc
  container_name: ft_malloc
  ports:
   - "1234:1234"
  volumes:
   - ft_malloc_vol:/ft_malloc
  restart: always


volumes:
 ft_malloc_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/ft_malloc'

